#!/usr/bin/env bash
#
# This file is part of REANA.
# Copyright (C) 2017, 2018, 2020, 2021, 2022, 2023, 2024, 2025 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -o errexit
set -o nounset

COMPONENT_NAME=reana-job-controller
DOCKER_IMAGE_NAME=docker.io/reanahub/$COMPONENT_NAME
PLATFORM="$(python -c 'import platform; print(platform.system())')"

# Verify that db container is running before continuing
_check_ready() {
    RETRIES=40
    while ! $2; do
        echo "==> [INFO] Waiting for $1, $((RETRIES--)) remaining attempts..."
        sleep 2
        if [ $RETRIES -eq 0 ]; then
            echo "==> [ERROR] Couldn't reach $1"
            exit 1
        fi
    done
}

_db_check() {
    docker exec --user postgres postgres__reana-job-controller bash -c "pg_isready" &>/dev/null
}

clean_old_db_container() {
    OLD="$(docker ps --all --quiet --filter=name=postgres__reana-job-controller)"
    if [ -n "$OLD" ]; then
        echo '==> [INFO] Cleaning old DB container...'
        docker stop postgres__reana-job-controller
    fi
}

start_db_container() {
    echo '==> [INFO] Starting DB container...'
    docker run --rm --name postgres__reana-job-controller -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d docker.io/library/postgres:14.10
    _check_ready "Postgres" _db_check
    db_container_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' postgres__reana-job-controller)
    if [[ -z $db_container_ip ]]; then
        # container does not have an IP when using podman
        db_container_ip="localhost"
    fi
    export REANA_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:mysecretpassword@$db_container_ip/postgres
}

stop_db_container() {
    echo '==> [INFO] Stopping DB container...'
    docker stop postgres__reana-job-controller
}

docker_build() {
    docker build -t $DOCKER_IMAGE_NAME .
}

docs_openapi() {
    FLASK_APP=reana_job_controller/app.py flask openapi create openapi.json
    diff -q -w openapi.json docs/openapi.json
    rm openapi.json
}

docs_sphinx() {
    sphinx-build -qnN docs docs/_build/html
}

format_black() {
    black --check .
}

format_prettier() {
    prettier -c .
}

format_shfmt() {
    shfmt -d .
}

lint_commitlint() {
    from=${2:-master}
    to=${3:-HEAD}
    pr=${4:-[0-9]+}
    if command -v commitlint >/dev/null 2>&1; then
        commitlint --from="$from" --to="$to"
    else
        npx commitlint --from="$from" --to="$to"
    fi
    found=0
    while IFS= read -r line; do
        commit_hash=$(echo "$line" | cut -d ' ' -f 1)
        commit_title=$(echo "$line" | cut -d ' ' -f 2-)
        commit_number_of_parents=$(git rev-list --parents "$commit_hash" -n1 | awk '{print NF-1}')
        # (i) skip checking release commits generated by Release Please
        if [ "$commit_number_of_parents" -le 1 ] && echo "$commit_title" | grep -qE "^chore\(.*\): release"; then
            continue
        fi
        # (ii) check presence of PR number
        if ! echo "$commit_title" | grep -qE "\(#$pr\)$"; then
            echo "✖   Headline does not end by '(#$pr)' PR number: $commit_title"
            found=1
        fi
        # (iii) check absence of merge commits in feature branches
        if [ "$commit_number_of_parents" -gt 1 ]; then
            if echo "$commit_title" | grep -qE "^chore\(.*\): merge "; then
                break # skip checking maint-to-master merge commits
            else
                echo "✖   Merge commits are not allowed in feature branches: $commit_title"
                found=1
            fi
        fi
    done < <(git log "$from..$to" --format="%H %s")
    if [ $found -gt 0 ]; then
        exit 1
    fi
}

lint_flake8() {
    flake8 .
}

lint_hadolint() {
    docker run -i --rm docker.io/hadolint/hadolint:v2.12.0 <Dockerfile
}

lint_jsonlint() {
    find . -name "*.json" -exec jsonlint -q {} \+
}

lint_manifest() {
    check-manifest
}

lint_markdownlint() {
    markdownlint-cli2 "**/*.md" -i "node_modules/**"
}

lint_pydocstyle() {
    pydocstyle reana_job_controller
}

lint_shellcheck() {
    find . -name "*.sh" -exec shellcheck {} \+
}

lint_yamllint() {
    yamllint .
}

python_tests() {
    clean_old_db_container
    start_db_container
    trap clean_old_db_container SIGINT SIGTERM SIGSEGV ERR
    pytest
    stop_db_container
}

all() {
    docker_build
    docs_openapi
    docs_sphinx
    format_black
    format_prettier
    format_shfmt
    lint_commitlint
    lint_flake8
    lint_hadolint
    lint_jsonlint
    lint_manifest
    lint_markdownlint
    lint_pydocstyle
    lint_shellcheck
    lint_yamllint
    python_tests
}

all_darwin() {
    # Tests are run inside the docker container because there is
    # no HTCondor Python package for MacOS
    lint_hadolint
    docker_build
    clean_old_db_container
    start_db_container
    RUN_TESTS_INSIDE_DOCKER="
    cd $COMPONENT_NAME &&
    apt update && apt-get -y install libkrb5-dev git shellcheck  &&
    pip install -r requirements.txt &&
    pip install -e .[all] && # Install test dependencies
    pip install black &&
    pip install flake8 &&
    pip install pydocstyle &&
    pip install check-manifest &&
    export REANA_SQLALCHEMY_DATABASE_URI=$REANA_SQLALCHEMY_DATABASE_URI &&
    ./run-tests.sh --all &&
    pytest"
    docker run -v "$(pwd)"/..:/code -ti $DOCKER_IMAGE_NAME bash -c "eval $RUN_TESTS_INSIDE_DOCKER"
    stop_db_container
}

help() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  --all                  Perform all checks [default]"
    echo "  --docker-build         Check Docker build"
    echo "  --docs-openapi         Check OpenAPI specification"
    echo "  --docs-sphinx          Check Sphinx docs build"
    echo "  --format-black         Check formatting of Python code"
    echo "  --format-prettier      Check formatting of Markdown etc files"
    echo "  --format-shfmt         Check formatting of shell scripts"
    echo "  --help                 Display this help message"
    echo "  --lint-commitlint      Check linting of commit messages"
    echo "  --lint-flake8          Check linting of Python code"
    echo "  --lint-hadolint        Check linting of Dockerfiles"
    echo "  --lint-jsonlint        Check linting of JSON files"
    echo "  --lint-manifest        Check linting of Python manifest"
    echo "  --lint-markdownlint    Check linting of Markdown files"
    echo "  --lint-pydocstyle      Check linting of Python docstrings"
    echo "  --lint-shellcheck      Check linting of shell scripts"
    echo "  --lint-yamllint        Check linting of YAML files"
    echo "  --python-tests         Check Python test suite"
}

if [ $# -eq 0 ]; then
    case $PLATFORM in
    Darwin*) all_darwin ;;
    *)
        all
        ;;
    esac
    exit 0
fi

arg="$1"
case $arg in
--all) all ;;
--help) help ;;
--docker-build) docker_build ;;
--docs-openapi) docs_openapi ;;
--docs-sphinx) docs_sphinx ;;
--format-black) format_black ;;
--format-prettier) format_prettier ;;
--format-shfmt) format_shfmt ;;
--lint-commitlint) lint_commitlint "$@" ;;
--lint-flake8) lint_flake8 ;;
--lint-hadolint) lint_hadolint ;;
--lint-jsonlint) lint_jsonlint ;;
--lint-manifest) lint_manifest ;;
--lint-markdownlint) lint_markdownlint ;;
--lint-pydocstyle) lint_pydocstyle ;;
--lint-shellcheck) lint_shellcheck ;;
--lint-yamllint) lint_yamllint ;;
--python-tests) python_tests ;;
*) echo "[ERROR] Invalid argument '$arg'. Exiting." && help && exit 1 ;;
esac
